spring:
  flyway:
    enabled: ${MYSQL_MIGRATIONS_ENABLED:true}

management:
  endpoint:
    health:
      group:
        readiness:
          include: "readinessState,db"
  health:
    redis:
      enabled: false
